sonar.projectKey=cohort-9-mern-7616-ghulam
sonar.projectName=Aether Notes
sonar.projectVersion=1.0

sonar.sources=backend/src,frontend/src
sonar.tests=backend/test,frontend/src
sonar.test.inclusions=backend/test/**/*.ts,frontend/src/**/__tests__/**/*.ts,frontend/src/**/__tests__/**/*.tsx

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

sonar.coverage.exclusions=backend/src/server.ts,backend/src/config/database.ts,backend/src/lib/logger.ts,frontend/src/main.tsx,frontend/src/vite-env.d.ts,frontend/src/components/editor/**

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,frontend/src/**/__tests__/**

sonar.sourceEncoding=UTF-8
